[package]
name = "orion_pt_mnist"
version = "0.1.0"

[dependencies]
starknet = "2.0.2"
orion = { git = "https://github.com/gizatechxyz/orion.git" }
layer2 = {path = "crates/layer2"}
layer3 = {path = "crates/layer3"}
layer4 = {path = "crates/layer4"}

[workspace]
members = [
    "crates/layer2",
    "crates/layer3",
    "crates/layer4",
]

[[target.starknet-contract]]