[package]
name = "inference"
version = "0.1.0"
edition = "2023_10"

[dependencies]
starknet = "2.0.2"
node_fc1_bias = { path = "../initializers/node_fc1_bias"} 
node_fc2_bias = { path = "../initializers/node_fc2_bias"} 
node_onnx_matmul_12 = { path = "../initializers/node_onnx_matmul_12"} 
node_onnx_matmul_13 = { path = "../initializers/node_onnx_matmul_13"} 

orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "8ff7389" } 
[lib]
sierra-text = true

[[target.starknet-contract]]

